mariocstweb/Boolbnb-team-5

package-lock.json, resources/scss/app.scss, resources/views/admin/apartments/show.blade.php
=> add grafic show

app/Http/Controllers/ApartmentController.php, app/Models/Apartment.php, resources/views/admin/apartments/create.blade.php, resources/views/admin/apartments/edit.blade.php, resources/views/admin/apartments/show.blade.php, resources/views/includes/apartment/form.blade.php
=> added form edit and create

package-lock.json, resources/scss/app.scss, resources/views/admin/apartments/index.blade.php
=> added layout index

resources/views/admin/apartments/index.blade.php, resources/views/includes/apartment/form.blade.php
refactoring visible status done
=> refactoring visible status

app/Http/Controllers/ApartmentController.php, app/Http/Requests/StoreApartmentRequest.php, app/Http/Requests/UpdateApartmentRequest.php
=> all validation

resources/js/delete_confirmation.js, resources/views/admin/apartments/trash.blade.php, resources/views/includes/modal.blade.php, resources/views/layouts/app.blade.php, vite.config.js
added bootstrap modal into trash
=> 10 bootstrap 5 modal

resources/js/image_preview.js, resources/views/admin/apartments/create.blade.php, resources/views/admin/apartments/edit.blade.php, vite.config.js
=> Preview cover

app/Http/Controllers/MessageController.php, app/Models/Apartment.php, app/Models/Message.php, database/factories/MessageFactory.php, database/migrations/2024_04_19_161436_create_messages_table.php, database/migrations/2024_04_19_162642_add_apartment_id_to_messages_table.php
=> 18 messages table

app/Http/Controllers/SponsorController.php, app/Models/Apartment.php, app/Models/Sponsor.php, database/factories/SponsorFactory.php, database/migrations/2024_04_19_162642_add_apartment_id_to_messages_table.php, database/migrations/2024_04_19_163357_create_sponsors_table.php, database/migrations/2024_04_19_164741_apartment_sponsor_table.php
=> 20 sponsors table

resources/scss/_button.scss, resources/views/auth/register.blade.php, resources/views/includes/layouts/navbar.blade.php, resources/views/sponsor/index.blade.php
=> Grafic sponsor

resources/scss/_button.scss, resources/views/admin/apartments/show.blade.php
=> Fix grafic show

app/Http/Controllers/ApartmentController.php, resources/scss/_form.scss, resources/views/includes/apartment/form.blade.php
=> fixed form

resources/views/admin/apartments/show.blade.php
=> added breadcrumb into show

config/apartments.php, resources/views/admin/apartments/show.blade.php
=> added description show

resources/views/admin/apartments/index.blade.php, resources/views/admin/apartments/show.blade.php, resources/views/includes/apartment/form.blade.php, resources/views/includes/layouts/navbar.blade.php
=> Align breadcrumb

app/Http/Controllers/Auth/RegisteredUserController.php, resources/views/auth/register.blade.php
=> Register validation

app/Http/Controllers/ApartmentController.php, app/Models/Apartment.php, config/apartments.php, database/seeders/ApartmentSeeder.php
added user id relation to apartments
=> added user id realtion

app/Http/Controllers/ApartmentController.php
added auth user id with apartment id
=> added auth user id with apartment id

resources/views/admin/apartments/index.blade.php, resources/views/admin/apartments/trash.blade.php
added modal into apartments index
=> added modal into apartments index

app/Http/Controllers/ApartmentController.php, database/factories/MessageFactory.php, database/seeders/DatabaseSeeder.php, resources/views/admin/apartments/index.blade.php, resources/views/admin/apartments/show.blade.php, resources/views/includes/layouts/navbar.blade.php, routes/web.php
added factori and relation message
=> added factori and relation message

resources/scss/_show.scss, resources/views/admin/apartments/show.blade.php
=> Card sponsor show

app/Http/Controllers/StatisticController.php, database/seeders/DatabaseSeeder.php, resources/js/grafic.js, resources/views/admin/dashboard.blade.php, resources/views/admin/statistic.blade.php, routes/web.php, vite.config.js
=> Dashboard data

app/Http/Controllers/ApartmentController.php, resources/scss/_index.scss, resources/views/admin/apartments/index.blade.php, resources/views/admin/apartments/show.blade.php, resources/views/sponsor/index.blade.php
=> 52 sponsor buttons

app/Http/Controllers/ApartmentController.php, app/Http/Controllers/DashboardController.php
=> refactoring pagination

resources/views/includes/layouts/navbar.blade.php
added active class into navbar links
=> added active class into navbar links

resources/js/address.js, resources/views/includes/apartment/form.blade.php
=> fixed address input

resources/scss/app.scss, resources/views/profile/edit.blade.php, resources/views/profile/partials/delete-user-form.blade.php, resources/views/profile/partials/update-password-form.blade.php, resources/views/profile/partials/update-profile-information-form.blade.php
=> edit grafic profile

package-lock.json, package.json, resources/js/map-show.js, resources/views/admin/apartments/show.blade.php, routes/web.php
=> finished maps show

app/Http/Controllers/ApartmentController.php, resources/js/check_payment.js, resources/views/admin/apartments/sponsor.blade.php, resources/views/sponsor/includes/payment.blade.php, vite.config.js
=> added radio payment

app/Http/Controllers/Api/ApartmentsController.php, routes/api.php
=> add call api

app/Http/Controllers/Api/ApartmentsController.php, routes/api.php
=> add api show

app/Http/Controllers/Api/ApartmentsController.php, app/Http/Controllers/Api/ServicesController.php, routes/api.php
added filter apartments and services
=> Filter apartments and services

app/Http/Controllers/Api/FilterServiceController.php, routes/api.php
added service route apartments
=> added service route apartments

app/Http/Controllers/Api/ApartmentsController.php
=> add services in th show

app/Http/Controllers/Api/ApartmentsController.php, app/Http/Controllers/Api/FilterController.php, routes/api.php
=> Filter controller

app/Http/Controllers/Api/MessageController.php, app/Http/Controllers/MessageController.php, app/Models/Message.php, database/factories/MessageFactory.php, database/migrations/2024_04_19_161436_create_messages_table.php, resources/views/admin/apartments/show.blade.php, resources/views/admin/messages/index.blade.php, routes/api.php, routes/web.php
add message api and controller
=> add message api and controller

app/Http/Controllers/Api/MessageController.php, app/Http/Controllers/MessageController.php, app/Models/Message.php, resources/views/admin/apartments/show.blade.php
=> fix content a text

app/Models/Session.php, database/migrations/2024_05_02_152432_create_sessions_table.php, resources/views/admin/messages/index.blade.php, resources/views/includes/layouts/navbar.blade.php, routes/api.php
=> add session

app/Http/Controllers/Api/FilterController.php
=> refactoring services filter

app/Http/Controllers/DashboardController.php, resources/views/admin/apartments/index.blade.php, resources/views/admin/dashboard.blade.php
=> add grafic in dashboard

app/Http/Controllers/ApartmentController.php, app/Models/Apartment.php
=> fixed messages order

app/Http/Controllers/Api/ApartmentsController.php, resources/js/map-show.js
=> add api views and message

app/Http/Controllers/Api/UserController.php, app/Http/Controllers/Auth/RegisteredUserController.php, app/Models/User.php, database/factories/UserFactory.php, database/migrations/2024_05_08_110354_add_birthday_to_users_table.php, database/seeders/DatabaseSeeder.php, resources/views/includes/layouts/navbar.blade.php, routes/api.php
=> Add api and birthday user

resources/scss/_index.scss, resources/views/admin/apartments/index.blade.php
=> add responsive index

resources/views/admin/dashboard.blade.php
=> added dashboard responsive

resources/scss/_nav.scss, resources/scss/app.scss, resources/views/admin/apartments/show.blade.php, resources/views/admin/apartments/sponsor.blade.php, resources/views/admin/apartments/statistics.blade.php, resources/views/admin/apartments/trash.blade.php, resources/views/admin/messages/index.blade.php, resources/views/auth/login.blade.php, resources/views/auth/register.blade.php, resources/views/includes/layouts/navbar.blade.php, resources/views/sponsor/includes/payment.blade.php
=> Responsive login and regiser

resources/views/includes/layouts/navbar.blade.php
=> added dropdown icon

resources/views/includes/apartment/form.blade.php
=> refactoring form layout

app/Http/Controllers/ApartmentController.php, app/Models/Apartment.php, config/filesystems.php, resources/views/admin/apartments/index.blade.php
=> added storage links

app/Http/Controllers/ApartmentController.php, resources/js/image_preview.js
=> fix change photo
